### ISSUE TITLE
Issues with Response from Pocket

### ISSUE THREAD

**Issue by greg-harrison** [vicchi/node-getpocket#1]
Hey Vicchi,

I really like this wrapper for the Pocket API, but I'm having an issue with JSON.stringify(options) for the body value in send.

I'm trying to send an array to Pocket (I have Modify credentials), but every time I run it, I get
`{ action_results: [ false, false ], status: 1 }` as the response object from Pocket.  

I was wondering if it has to do with the opts being stringified for both Modify and Send calls, since Pocket is expecting an array on the request.

Thanks for making this. I really like it!

**Comment by vicchi** [comment]
Thanks for this; can you possibly put together a test case as a Gist so I can be sure that we're looking at the same thing?

**Comment by greg-harrison** [comment]
Sure! Here's a link. https://gist.github.com/8bitg/29050029371ba15f74ee

 You'll need to run an npm install and update the config file with your Pocket creds before running the script. Thanks for taking the time to look at this! It may be the formatting of my request and nothing on the part of GetPocket.

**Comment by vicchi** [comment]
Great! I'll take a look as soon as I have a spare moment or three

**Comment by greg-harrison** [comment]
The issue was on my end. Sorry for the alarm! Thanks so much for this project, it was very helpful for me.
